### ISSUE TITLE
请教下 客户端和服务器端数据不同步了

### ISSUE THREAD

**Issue by cobola** [maodouio/meteor-lean-startup-camp#11]
client端 console 用 Posts.find() 是空

server端 meteor mongo 进入后 用 db.posts.find() 查数据 有数据

不知道是不是mongo数据库的原因 我用meteor update升级 好像是升级到mongodb 3.0 可是用 meteor shell进入后显示的还是 meteor 2.6

具体的代码 

meteorbb 项目 dev分支 

/lib/router/posts.js 第30行

可以看到 count是0 

这样的问题 怎么查 目前还没有头绪...

**Comment by cobola** [comment]
应该不是数据库的原因 是是我的问题

**Comment by kevingzhang** [comment]
Have you subscribe and publish data to client?

**Comment by cobola** [comment]
搞定了。。删掉了一个属性 然后搜索的时候 就搜不到结果了
