### ISSUE TITLE
IOS 如何打包和发布

### ISSUE THREAD

**Issue by luckyyang** [maodouio/meteor-lean-startup-camp#13]

**Comment by wuyuedefeng** [comment]
在项目文件夹下执行
meteor build ~/Desktop/iosApp --server http://xx.meteor.com

http://xx.meteor.com 指服务器地址的域名

执行后会在桌面生成一个iosApp的文件夹，内有个ios文件夹存放着生成的项目，然后用xcode打开   ，其他操作和 原生项目操作一样
