### ISSUE TITLE
android 如何打包和发布

### ISSUE THREAD

**Issue by luckyyang** [maodouio/meteor-lean-startup-camp#14]

**Comment by guoyoujin** [comment]
Meteor apk 打包
官方api：https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store

首先进入你的所要打包的meteor工程

一.生成apk 

meteor build ~/build-output-directory --server=guoyoujinlove.meteor.com
上面guoyoujinlove.meteor.com就是你要指向的ip地址，改成你所需要的ip即可，运行完上面的命令之后他会在~/build-output-directory目录里面生成两个文件一个是android文件夹一个是ios文件夹，我们进入android文件夹，可以看到一个unaligned.apk文件，他就是我们要打包的apk啦，
执行命令

二.给apk签名（如果你没签名文件请先看步骤三，localmarket.keystore既为签名文件）

cd ~/build-output-directory/android
我们就进入了~/android文件夹了，好了我们可以为apk签名了，运行命令
jarsigner -digestalg SHA1 unaligned.apk localmarket.keystore
如果报错可能是你没有localmarket.keystore 文件，或者叫另外一个名字，这个时候你就按照步骤三执行命令再来走步骤二

三.生成签名文件：

ok签名成功了，注意上面的localmarket.keystore文件是签名文件，使用keytool工具签名，这个前提是你得有android－sdk和jdk，如果你有这些环境即可运行命令：
keytool -genkey localmarket.keystore -keyalg RSA \ -keysize 2048 -validity 10000
运行后会让你输入密码以及一些你的签名信息，你只要按照要求输入你自己的信息即可成功生成keystore

四.优化apk

最后还可以对你的apk进行优化一下，提高apk的性能，执行以下命令（ 下面unaligned.apk是你签名成功的apk，producation.apk就是你优化过后的apk了，你只要发布这个apk就行了）
~/.meteor/android_bundle/android-sdk/build-tools/20.0.0/zipalign 4 \ unaligned.apk production.apk

五.利用eclipse打包签名

当我执行完上面的步骤，在手机上安装apk的时候，发现安装不上，初步认为是sdk的问题，没关系我们还有打包apk的办法，首先你的保证你走完了步骤一，假设你成功执行了步骤一，接下来输入命令：
cd ~/build-output-directory/android
在这个文件夹下你可以看到一个project的文件夹，如果你是android开发者，并且你安装了eclipse以及sdk和jdk（缺一不可），先请你打开eclipse，点击
file －> imoprt  －> Android —>Existing android code into workspace    

找到在 ~/build-output-directory/android下的project文件夹把它导入到你的eclipse工程里面，
你会看到两个项目CordovaApp-CordovaLib和你创建的meteor项目文件名 相同的项目，假设他叫localmraket,
好的接下来我们选中项目右击选择Run As命令后，等一会即可生成apk，他在这个工程的bin目录下叫做localmarket.apk,
先别着急，还没给apk签名，你先准备好你的签名文件，
然后选中项目右击选择AndroidTools 在选中Export Signed Application Package一路跟着提示输入信息即可完成签名apk
