### ISSUE TITLE
服务号、订阅号的介绍（区别）

### ISSUE THREAD

**Issue by luckyyang** [maodouio/meteor-lean-startup-camp#16]
https://mp.weixin.qq.com/

![image](https://cloud.githubusercontent.com/assets/1963646/6763380/631c12e0-cfb4-11e4-9c59-c80ff0370200.png)

**Comment by cobola** [comment]
现在自定义菜单 所有公共号都开放了

**Comment by luckyyang** [comment]
红色部分应该是都需要认证的吧，也就是说要收费300块

**Comment by luckyyang** [comment]
自定义菜单不需要收费
