### ISSUE TITLE
客户端执行Posts.remove({})无效的问题的解释

### ISSUE THREAD

**Issue by FrankyYang** [maodouio/meteor-lean-startup-camp#17]
原文链接：https://teamgaslight.com/blog/how-to-remove-all-elements-from-a-meteor-collection

描述：Starting in 0.5.8, client-only code such as event handlers may only update or remove a single document at a time, specified by _id.“ More…
从0.5.8开始，客户端代码，比如在event handlers里面的代码，每次只能更新或者删除一个文档，通过指定的_id来操作。

**Comment by luckyyang** [comment]
wiki 了 https://github.com/maodouio/meteor-lean-startup-camp/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%89%A7%E8%A1%8CPosts.remove(%7B%7D)%E6%97%A0%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E9%87%8A
