### ISSUE TITLE
Meteor-Chat项目修改到适配1.0.4的方法

### ISSUE THREAD

**Issue by FrankyYang** [maodouio/meteor-lean-startup-camp#18]
代码地址：https://github.com/tomblomfield/meteor-chat
代码download下来之后直接运行meteor会报错，无法启动server，在server正常启动之前需要做这些修改：
1，增加这个文件：
.meteor/release
文件内容：
METEOR@1.0.3.1

2，meteor add platform

这时候基本上就可以正常开启server了，但是发布消息按下回车的时候还是没有反应。这个阶段要做这些修改：
1，chat.coffee 做两处修改：
第二行改为：Messages = new Mongo.Collection "messages" 
第四行改为：if Meteor.isClient  

2，meteor add insecure

**Comment by luckyyang** [comment]
:+1:

**Comment by luckyyang** [comment]
wiki 了
