### ISSUE TITLE
accounts-ui包注册表单项的控制

### ISSUE THREAD

**Issue by FrankyYang** [maodouio/meteor-lean-startup-camp#19]
文档：http://docs.meteor.com/#/full/accounts_ui_config

Which fields to display in the user creation form. One of 'USERNAME_AND_EMAIL', 'USERNAME_AND_OPTIONAL_EMAIL', 'USERNAME_ONLY', or 'EMAIL_ONLY' (default).

代码：
Accounts.ui.config({
  requestPermissions: {
    facebook: ['user_likes'],
    github: ['user', 'repo']
  },
  requestOfflineToken: {
    google: true
  },
  passwordSignupFields: 'USERNAME_AND_OPTIONAL_EMAIL'
});

passwordSignupFields的四种选择：
1，用户名和邮件：'USERNAME_AND_EMAIL',
2，用户名，邮件可选： 'USERNAME_AND_OPTIONAL_EMAIL', 
3，只用户名：'USERNAME_ONLY',
4，只Email： 'EMAIL_ONLY'

**Comment by luckyyang** [comment]
I created a wiki for this issue: https://github.com/maodouio/meteor-lean-startup-camp/wiki/accounts-ui%E5%8C%85%E6%B3%A8%E5%86%8C%E8%A1%A8%E5%8D%95%E9%A1%B9%E7%9A%84%E6%8E%A7%E5%88%B6
