### ISSUE TITLE
微信聊天群里面一些资料链接

### ISSUE THREAD

**Issue by limingth** [maodouio/meteor-lean-startup-camp#21]
100米以内 8:03 AM
[Iron:Router的教程 : http://note.youdao.com/share/?id=6ed113ebae285b58ed77928c25a5c0bf&type=note]

北美开吻 8:05 AM
https://github.com/Slava/tern-meteor-sublime 用 Sublime 开发者写 js 这里有 meteor 的插件了

北美开吻 8:09 AM
http://almsaeedstudio.com/themes/AdminLTE/documentation/index.html

北美开吻 8:13 AM
http://almsaeedstudio.com/themes/AdminLTE/index2.html

吉洋 9:04 AM
http://almsaeedstudio.com/themes/AdminLTE/documentation/index.html

翟英昌 9:57 AM
https://github.com/limingth/meteor-lean-startup-camp/blob/master/the_best_meteor_packages_you_must_know-ZH.md

翟英昌 10:15 AM
http://pingxx.com/

shooter 10:37 AM
https://cnodejs.org/topic/51b030d9555d34c678e5fb2e DDP协议

youjin 11:47 AM
Android apk打包：https://github.com/meteor/meteor/wiki/How-to-submit-your-Android-app-to-Play-Store

北美开吻 12:32 PM
对于 meteor 数据这块有疑问的可以看这篇文章 https://medium.com/@stubailo/data-flow-from-the-database-to-the-ui-three-layers-of-meteor-d5e208b466c3

翟伟明 1:22 PM
https://www.jetbrains.com/webstorm/help/using-meteor.html

shooter 3:13 PM
求 youtebo 地址

100米以内 3:14 PM
https://github.com/limingth/meteor-lean-startup-camp/wiki/Ten-meteor-project-you-should-know

shooter 3:15 PM
https://www.youtube.com/watch?v=MbZnf9Fa8UE

shooter 3:17 PM
http://www.meteortuts.com/

100米以内 3:52 PM
https://github.com/limingth/meteor-lean-startup-camp/issues/17

100米以内 4:00 PM
https://github.com/limingth/meteor-lean-startup-camp/issues/18

100米以内 4:21 PM
http://www.manuel-schoebel.com/blog/iron-router-tutorial 这个tutorial大家一起来翻译一下吧？ 内容不多，代码占了大部分

100米以内 4:34 PM
http://meteortips.com/tutorial/custom-registration-form/ accounts-ui定制化的方法，也可以翻译一下，大家比较常用的。

**Comment by luckyyang** [comment]
wiki 了
