### ISSUE TITLE
推荐一个比较简单的左侧菜单模版

### ISSUE THREAD

**Issue by limingth** [maodouio/meteor-lean-startup-camp#22]
### meteor-ionic-example

[Demo] http://maodou-ionic-example.meteor.com
[Code] https://github.com/netanelgilad/meteor-ionic-example

**Comment by luckyyang** [comment]
wiki了：https://github.com/maodouio/meteor-lean-startup-camp/wiki/%E4%B8%80%E4%B8%AA%E6%AF%94%E8%BE%83%E7%AE%80%E5%8D%95%E7%9A%84%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95%E6%A8%A1%E7%89%88
