### ISSUE TITLE
北京Meteor学习交流微信群二维码

### ISSUE THREAD

**Issue by limingth** [maodouio/meteor-lean-startup-camp#27]
![image](https://cloud.githubusercontent.com/assets/1249369/13982296/20b0c102-f124-11e5-8300-46bd0642bc89.png)

**Comment by luckyyang** [comment]
群已经满了，想加的私信给我们吧

**Comment by zhongwus** [comment]
你好 我的微信是q359919199,能加群么谢谢

**Comment by sunbest110** [comment]
你好  我的微信号sunmeng1356，现在可以加群吗，我的 qq号919851388

**Comment by jiangtao** [comment]
@luckyyang 求加入。
Wechat: 470486732

**Comment by 526878729** [comment]
wechat: 343166031 please :)
