### ISSUE TITLE
如何选择 bootstrap & meteoric

### ISSUE THREAD

**Issue by luckyyang** [maodouio/meteor-lean-startup-camp#36]
https://i.reddit.com/r/Meteor/comments/2vj881/what_mobile_frontend_ui_framework_can_you/

> Bootstrap is a bit too heavy for a mobile app. Meteoric has done wonders in getting ionic into meteor and there is actually a boilerplate https://github.com/dalequi/meteor-meteoric-boilerplate you can start off of. If you're willing to go the extra mile to provide a native-like performance, you can try famous but to bootstrap fast, meteoric seems to be the more reasonable choice.

**Comment by kevingzhang** [comment]
Ionic is very mobile app oriented. It is not friendly to web site. So your app is only running on mobile app, yes, go for ionic (Meteoric)

**Comment by cobola** [comment]
如果可选两套皮肤就好了
