### ISSUE TITLE
客户端请求数据，图片加载后  app端怎么做缓存，避免每次都重新从服务器加载图片

### ISSUE THREAD

**Issue by wuyuedefeng** [maodouio/meteor-lean-startup-camp#37]

**Comment by kevingzhang** [comment]
If you are not using meteor, do it as what you did before, 
if you are using Meteor, there are many ways. If the picture is stored inside mongodb, you can subscribe it. if the pictures are in S3 ( or some CDN like that), it will be automatically cached by browser unless you disable the cache feature.

**Comment by luckyyang** [comment]
seem this issue is done, so close it. I created a wiki for this issue: https://github.com/maodouio/meteor-lean-startup-camp/wiki/%E5%9B%BE%E7%89%87%E5%A6%82%E4%BD%95%E7%BC%93%E5%AD%98
