### ISSUE TITLE
用ionic   键盘显示后页面上顶，键盘隐藏后页面不下来，页面下半部分变成空白

### ISSUE THREAD

**Issue by wuyuedefeng** [maodouio/meteor-lean-startup-camp#38]

**Comment by kevingzhang** [comment]
there are a few bugs reports related to this on https://github.com/meteoric/meteor-ionic/issues/130#issuecomment-87706446

Please go directly to the ionic project github page to follow the changes.

**Comment by limingth** [comment]
https://github.com/meteoric/meteor-ionic/issues/130 we have same issue as like, keyboard not showing up correctly in ios

https://github.com/driftyco/ionic-plugins-keyboard/issues/37

这是另外一个小组碰到的键盘问题，他们解决了，看看你们是不是同样问题

Note: after some tries, found that we have to **remove com.ionic.keyboard dependency inside meteor-ionic to fix the keyboard overlay input issue**

**Comment by wuyuedefeng** [comment]
yes, we solve it yet. thank you

**Comment by Hamasn** [comment]
Did anyone fix the issue? I got the same issue.
