### ISSUE TITLE
boilerplate structures for Meteor projects

### ISSUE THREAD

**Issue by luckyyang** [maodouio/meteor-lean-startup-camp#41]
- https://github.com/matteodem/meteor-boilerplate
- https://github.com/iron-meteor/iron-cli
- https://github.com/SachaG/Void

**Comment by luckyyang** [comment]
帮你生成 project 的文件结构

**Comment by cobola** [comment]
求类似 ionic resources 这样的cli  方便生成图标和splash

我现在是用ionic的 然后再手工拷贝过来

**Comment by luckyyang** [comment]
@cobola 你的问题可以提交一个新的 issue 来讨论
