### ISSUE TITLE
Test for maillist

### ISSUE THREAD

**Issue by limingth** [maodouio/meteor-lean-startup-camp#6]
check if you can receive the notification. 

if ok, reply something....

**Comment by realdawn** [comment]
ok

------------------ 原始邮件 ------------------
发件人: "Li Ming";notifications@github.com;
发送时间: 2015年3月14日(星期六) 下午3:36
收件人: "limingth/meteor-lean-startup-camp"meteor-lean-startup-camp@noreply.github.com; 

主题: [meteor-lean-startup-camp] Test for maillist (#6)

check if you can receive the notification. 

if ok, reply something....
