### ISSUE TITLE
To learn meteor, should i start with javascript, or directly start from coffeescript / typescript ?

### ISSUE THREAD

**Issue by zhifengjiang** [maodouio/meteor-lean-startup-camp#7]
i have little knowledge about javascript, so i about to start learning javascript. but i wonder need i start from javascript or just go to coffeescript / typescript?  
anyhow,  i won't using javascript to develop meteor , any suggestion for choosing between coffeescript and typescript.?

**Comment by guokr321** [comment]
我自己感觉，这种障碍是，大部分资料都是写的，你如果对js不熟悉，肯定要先学js吧，毕竟要读代码的，js切到coffee似乎用不了太费劲，官网上就有语法映射

At 2015-03-15 13:37:13, "sammychiang" notifications@github.com wrote:

i have little knowledge about javascript, so i about to start learning javascript. but i wonder need i start from javascript or just go to coffeescript / typescript?

anyhow, i won't using javascript to develop meteor , please introduce what should be choosen between coffeescript and typescript.?
